#!/bin/bash

#this script automatically updates the passwords and keys in the settings files
#it copies the settings files from the build_files folder and automatically puts them in the right folder

#######################

#this script should only be run at setup, seeing as it changes the jwt key
#any future changes should be made in the config files themselves

#######################


get_concent() {
	read -r -p "$1 [Y/n]" response
	if [[ "$response" =~ ^([yY][eE][sS]|[yY]|)$ ]]
	then
    		return 1
	else
    		return 0
	fi
}

docker --version 1>/dev/null || sudo apt install docker.io
docker-compose 2>/dev/null || python3 -m pip install docker-compose || sudo apt install docker-compose

if [ -d pgdata ]; then
	if get_concent "Installation detected. Want to reïnstall? (all data will be lost!)" $1; then
		#don't reinstall
		exit
	else
		sudo rm -rf pgdata
		rm docker-compose.yml
		rm postgresql/init.sql
		rm DomoticControl/DomoticControl/data/settings.yaml
	fi
fi


if ! get_concent "Autogenerated domotic password?" $1; then
	domotic_password=`dd if=/dev/urandom count=1 bs=40 | base64 -w 0 | sed 's/\//-/g'`
else 
	read -rs -p "Enter domotic password " domotic_password
fi

if ! get_concent "Autogenerated api password?" $1
then
	api_password=`dd if=/dev/urandom count=1 bs=40 | base64 -w 0 | sed 's/\//-/g'`
else
	read -rs -p "Enter API password " api_password
fi

echo generating key
key=`dd if=/dev/urandom count=1 bs=2048 | base64 -w 0 | sed 's/\//-/g'`
echo $key
echo $api_password
echo $domotic_password

rm docker-compose.yml
sed "s/{API_KEY}/$key/g; s/{API_PASSWORD}/$api_password/g; s/{DOMOTIC_PASSWORD}/$domotic_password/g" setup_files/docker-compose.yml.template >  docker-compose.yml

rm postgresql/init.sql
sed "s/{API_KEY}/$key/g; s/{API_PASSWORD}/$api_password/g; s/{DOMOTIC_PASSWORD}/$domotic_password/g" setup_files/init.sql.template >  postgresql/init.sql

rm DomoticControl/DomoticControl/data/settings.yaml
sed "s/{API_KEY}/$key/g; s/{API_PASSWORD}/$api_password/g; s/{DOMOTIC_PASSWORD}/$domotic_password/g" setup_files/settings.yaml.template > DomoticControl/DomoticControl/data/settings.yaml

(cd postgresql && docker build -t domotic_postgresql .)
(cd DomoticControl && docker build -t domoticcontrol .)

docker image prune

if ! get_concent "Want to start DomoticControl?" $1; then
	docker-compose up
fi
